### ISSUE TITLE
Build NCNN on Windows10

### ISSUE THREAD

**Issue by HaiderAbasi** [HaiderAbasi/Raspberry-Pi-4-Computer-Vision-#15]
https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-windows-x64-using-visual-studio-community-2017

**Comment by HaiderAbasi** [comment]
The following binaries were generated from building ncnn on Windows 10. 
Waiting for model evaluation results to come through. 🤞 

![Image](https://user-images.githubusercontent.com/49869365/221608815-640588b5-ca7a-4f75-83eb-ea47708f950b.png)

**Comment by noshluk2** [comment]
Yra use python . Udemy Courses will always be on Python
